--Tabelas de controle

CREATE TABLE AUTORIZACOES_SNT(
    --Referência: 'Transplante de intestino delgado' tem 32
    TIPO VARCHAR2(40) NOT NULL,
    
    CONSTRAINT PK_AUTORIZACOES_SNT PRIMARY KEY(TIPO)
);

CREATE TABLE TIPOS_EXAME(
    --Referência: 'Ressonância Magnética da Coluna Vertebral com Contraste' tem 55
    TIPO VARCHAR2(70) NOT NULL,
    
    CONSTRAINT PK_TIPOS_EXAME PRIMARY KEY(TIPO)
);

CREATE TABLE TIPO_ORGAO(
    --Referência: 'Músculo esternocleidomastóideo' tem 30. Órgãos transplantáveis são menores
    NOME VARCHAR2(30) NOT NULL,
    
    CONSTRAINT PK_TIPO_ORGAO PRIMARY KEY(NOME)
);

CREATE TABLE EQUIPAMENTO(
    --Referência: 'Sistema de Ablação por Radiofrequência Guiada por Ultrassom de Alta Resolução' tem 77
    TIPO VARCHAR2(80) NOT NULL,
    DESCRICAO VARCHAR2(50),
    
    CONSTRAINT PK_EQUIPAMENTO PRIMARY KEY(TIPO),
    CONSTRAINT CK_EQUIPAMENTO_UPPER_DESCRICAO CHECK(UPPER(DESCRICAO) = DESCRICAO)
);

CREATE TABLE ESPECIALIDADES_MEDICAS(
    --https://www.grupomedcof.com.br/blog/55-especialidades-medicas/
    --Referência: 'Radiologia e diagnóstico por imagem' tem 39
    NOME VARCHAR2(40),
    
    CONSTRAINT PK_ESPECIALIDADES_MEDICAS PRIMARY KEY(NOME)
);

--Especialização de Pessoa
CREATE TABLE PESSOA(
    --raw(8) -> mais de 18 quintilhões de combinações, 87.4 bilhões de opções pra cada brasileiro
    --Impossível de adivinhar, chance minúscula de colisões
    --substr(1,16) porque ele corta o texto de SYS_GUID(), que está em hexa (dobro dos caracteres)
    ID RAW(8) DEFAULT SUBSTR(SYS_GUID(), 1, 16) NOT NULL,
    CPF CHAR(14) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    ESTADO CHAR(2),
    CIDADE VARCHAR2(50),
    BAIRRO VARCHAR2(30),
    RUA VARCHAR2(30),
    --5 caracteres, 0 decimais
    NUMERO NUMBER(5, 0),
    TELEFONE1 CHAR(14),
    TELEFONE2 CHAR(14),
    
    CONSTRAINT PK_PESSOA PRIMARY KEY(ID),
    
    CONSTRAINT UNIQUE_PESSOA_CPF UNIQUE(CPF),
    CONSTRAINT CK_PESSOA_CPF CHECK(REGEXP_LIKE(CPF, '[0-9]{3}\.[0-9]{3}\.[0-9]{3}\-[0-9]{2}')),
    --Verificação dos últimos dígitos do CPF ficam pra aplicação
    
    CONSTRAINT CK_PESSOA_NOME_UPPER CHECK(UPPER(NOME) = NOME),
    CONSTRAINT CK_PESSOA_ESTADO CHECK (ESTADO IN (
        'AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA',
        'PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'
    )),
    CONSTRAINT CK_PESSOA_CIDADE_UPPER CHECK(UPPER(CIDADE) = CIDADE),
    CONSTRAINT CK_PESSOA_BAIRRO_UPPER CHECK(UPPER(BAIRRO) = BAIRRO),
    CONSTRAINT CK_PESSOA_RUA_UPPER CHECK(UPPER(RUA) = RUA),
    
    CONSTRAINT CK_PESSOA_NUMERO_POSITIVO CHECK(NUMERO > 0),
    CONSTRAINT CK_PESSOA_TELEFONE1 CHECK(TELEFONE1 IS NULL OR REGEXP_LIKE(TELEFONE1, '\([0-9]{2}\)9[0-9]{4}\-[0-9]{4}')),
    CONSTRAINT CK_PESSOA_TELEFONE2 CHECK(TELEFONE2 IS NULL OR REGEXP_LIKE(TELEFONE2, '\([0-9]{2}\)9[0-9]{4}\-[0-9]{4}'))
);

CREATE TABLE FUNCIONARIO(
    PESSOA RAW(8) NOT NULL,
    FUNCAO CHAR(1) NOT NULL,
    
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(PESSOA),
    CONSTRAINT FK_FUNCIONARIO_PESSOA FOREIGN KEY(PESSOA) REFERENCES PESSOA(ID),
    
    --E = ENFERMEIRO, M = MÉDICO
    CONSTRAINT CK_FUNCIONARIO_FUNCAO CHECK(FUNCAO IN ('E', 'M'))
);

CREATE TABLE MEDICO(
    FUNCIONARIO RAW(8) NOT NULL,
    CRM CHAR(9) NOT NULL,
    VALIDADE_CRM DATE NOT NULL,
    ESPECIALIZACAO VARCHAR2(40) NOT NULL,
    
    CONSTRAINT PK_MEDICO PRIMARY KEY(FUNCIONARIO),
    CONSTRAINT FK_MEDICO_FUNCIONARIO FOREIGN KEY(FUNCIONARIO) REFERENCES FUNCIONARIO(PESSOA),
    CONSTRAINT FK_MEDICO_ESPECIALIZACAO FOREIGN KEY(ESPECIALIZACAO) REFERENCES ESPECIALIDADES_MEDICAS(NOME),
    
    --https://www.contabilizei.com.br/contabilidade-online/crm-medico/
    CONSTRAINT CK_MEDICO_CRM CHECK(REGEXP_LIKE(CRM, '^[0-9]{1,6}-[A-Z]{2}$'))
    --Não é possível avaliar se a validade do CRM se encontra no futuro, a aplicação vai precisar cuidar disso
);

CREATE TABLE ENFERMEIRO(
    FUNCIONARIO RAW(8) NOT NULL,
    COREN VARCHAR2(14) NOT NULL,
    VALIDADE_COREN DATE NOT NULL,
    
    CONSTRAINT PK_ENFERMEIRO PRIMARY KEY(FUNCIONARIO),
    CONSTRAINT FK_ENFERMEIRO_FUNCIONARIO FOREIGN KEY(FUNCIONARIO) REFERENCES FUNCIONARIO(PESSOA),
    
    --https://www.corensc.gov.br/entenda-as-regras-do-uso-do-carimbo-para-profissionais-da-enfermagem/
    CONSTRAINT CK_ENFERMEIRO_COREN CHECK(REGEXP_LIKE(COREN, '^[0-9]{1,6}-(ENF|OBST|TE|AE|PAR|AUT|AT) [A-Z]{2}$'))
    --Não é possível avaliar se a validade do COREN se encontra no futuro, a aplicação vai precisar cuidar disso
);

CREATE TABLE PACIENTE(
    PESSOA RAW(8) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    NASCIMENTO DATE NOT NULL,
    OBITO DATE,
    COR VARCHAR2(8) NOT NULL,
    --5 digítos, 2 decimais
    PESO NUMBER(5,2) NOT NULL,
    TELEFONE_EMERGENCIA1 CHAR(14),
    TELEFONE_EMERGENCIA2 CHAR(14),
    
    CONSTRAINT PK_PACIENTE PRIMARY KEY(PESSOA),
    CONSTRAINT FK_PACIENTE_PESSOA FOREIGN KEY(PESSOA) REFERENCES PESSOA(ID),
    
    --M = MASCULINO, F = FEMININO
    CONSTRAINT CK_PACIENTE_SEXO CHECK(SEXO IN ('M', 'F')),
    --Não é possível avaliar se a data de nascimento está no passado, fica pra aplicação controlar
    --Classificação do IBGE
    CONSTRAINT CK_PACIENTE_COR CHECK(COR IN ('BRANCO', 'PRETO', 'PARDO', 'AMARELO', 'INDIGENA')),
    CONSTRAINT CK_PACIENTE_PESO_POSITIVO CHECK(PESO > 0),
    
    CONSTRAINT CK_PACIENTE_TELEFONE_EMERGENCIA1 CHECK(TELEFONE_EMERGENCIA1 IS NULL OR REGEXP_LIKE(TELEFONE_EMERGENCIA1, '\([0-9]{2}\)9[0-9]{4}\-[0-9]{4}')),
    CONSTRAINT CK_PACIENTE_TELEFONE_EMERGENCIA2 CHECK(TELEFONE_EMERGENCIA2 IS NULL OR REGEXP_LIKE(TELEFONE_EMERGENCIA2, '\([0-9]{2}\)9[0-9]{4}\-[0-9]{4}'))
);

CREATE TABLE ESPECIALIZACAO_PACIENTE(
    PACIENTE RAW(8) NOT NULL,
    TIPO CHAR(1) NOT NULL,
    
    CONSTRAINT PK_ESPECIALIZACAO_PACIENTE PRIMARY KEY(PACIENTE, TIPO),
    CONSTRAINT FK_ESPECIALIZACAO_PACIENTE_PACIENTE FOREIGN KEY(PACIENTE) REFERENCES PACIENTE(PESSOA),
    
    --D = DOADOR, R = RECEPTOR
    CONSTRAINT CK_ESPECIALIZACAO_PACIENTE_TIPO CHECK(TIPO IN ('D', 'R'))
);


--Hospital

CREATE TABLE HOSPITAL(
    --http://cnsaude.org.br/wp-content/uploads/2022/07/CNSAUDE-FBH-CENARIOS-2022.pdf
    --Em 2022, o Brasil tinha 7191 hospitais
    --raw(6) -> 281.474 trilhões de combinações, mais de 39.142 bilhões de opções pra cada hospital
    --Impossível de adivinhar, chance minúscula de colisões
    --substr(1,12) porque ele corta o texto de SYS_GUID(), que está em hexa (dobro dos caracteres)
    ID RAW(6) DEFAULT SUBSTR(SYS_GUID(), 1, 12) NOT NULL,
    CNES CHAR(7) NOT NULL,
    NOME VARCHAR2(30) NOT NULL,
    CNPJ CHAR(18) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CIDADE VARCHAR2(50) NOT NULL,
    BAIRRO VARCHAR2(30) NOT NULL,
    RUA VARCHAR2(30) NOT NULL,
    --5 caracteres, 0 decimais
    NUMERO NUMBER(5, 0) NOT NULL,
    NUMERO_SALAS_INTERNACAO NUMBER(4,0),
    NUMERO_SALAS_CIRURGIA NUMBER(4,0),
    
    CONSTRAINT PK_HOSPITAL PRIMARY KEY(ID),
    CONSTRAINT UNIQUE_HOSPITAL_CNES UNIQUE(CNES),
    CONSTRAINT UNIQUE_HOSPITAL_ENDERECO UNIQUE(ESTADO, CIDADE, BAIRRO, RUA, NUMERO),
    
    CONSTRAINT CK_HOSPITAL_CNES CHECK(REGEXP_LIKE(CNES, '^[0-9]{1,7}$')),
    CONSTRAINT CK_HOSPITAL_CNPJ CHECK(REGEXP_LIKE(CNPJ, '[0-9]{2}\.[0-9]{3}\.[0-9]{3}/[0-9]{4}-[0-9]{2}')),
    
    CONSTRAINT CK_HOSPITAL_UPPER_NOME CHECK(UPPER(NOME) = NOME),
    
    CONSTRAINT CK_HOSPITAL_ESTADO CHECK (ESTADO IN (
        'AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA',
        'PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'
    )),
    
    CONSTRAINT CK_HOSPITAL_UPPER_CIDADE CHECK(UPPER(CIDADE) = CIDADE),
    CONSTRAINT CK_HOSPITAL_UPPER_BAIRRO CHECK(UPPER(BAIRRO) = BAIRRO),
    CONSTRAINT CK_HOSPITAL_UPPER_RUA CHECK(UPPER(RUA) = RUA),
    
    CONSTRAINT CK_HOSPITAL_NUMERO_POSITIVO CHECK(NUMERO > 0),
    
    CONSTRAINT CK_HOSPITAL_NUMERO_SALAS_INTERNACAO_POSITIVO CHECK(NUMERO_SALAS_INTERNACAO > 0),
    CONSTRAINT CK_HOSPITAL_NUMERO_SALAS_CIRURGIA_POSITIVO CHECK(NUMERO_SALAS_CIRURGIA > 0)
);

--Laboratório

CREATE TABLE LABORATORIO(
    --Assumindo que todo hospital tem 10 laboratórios, que já é uma extrapolação grande
    --raw(6) -> 281.474 trilhões de combinações, mais de 3.914 bilhões de opções pra cada hospital
    --Impossível de adivinhar, chance minúscula de colisões
    --substr(1,12) porque ele corta o texto de SYS_GUID(), que está em hexa (dobro dos caracteres)
    ID RAW(6) DEFAULT SUBSTR(SYS_GUID(), 1, 12) NOT NULL,
    HOSPITAL RAW(6) NOT NULL,
    NOME VARCHAR2(30) NOT NULL,
    --DAY(0) e SECOND(0) impedem valores fracionários
    ABERTURA INTERVAL DAY(0) TO SECOND(0) NOT NULL,
    FECHAMENTO INTERVAL DAY(0) TO SECOND(0) NOT NULL,
    ESTADO VARCHAR2(2) NOT NULL,
    CIDADE VARCHAR2(50) NOT NULL,
    BAIRRO VARCHAR2(30) NOT NULL,
    RUA VARCHAR2(30) NOT NULL,
    NUMERO NUMBER(5,0) NOT NULL,
    
    CONSTRAINT PK_LABORATORIO PRIMARY KEY(ID),
    CONSTRAINT UNIQUE_LABORATORIO_NOME_POR_HOSPITAL UNIQUE(HOSPITAL, NOME),

    CONSTRAINT FK_LABORATORIO_HOSPITAL FOREIGN KEY(HOSPITAL) REFERENCES HOSPITAL(ID),
    
    CONSTRAINT CK_LABORATORIO_NOME_UPPER CHECK(UPPER(NOME) = NOME),
    
    --Verifica se é um horário válido (sem dia nem segundo)
    CONSTRAINT CK_LABORATORIO_ABERTURA_CHECK CHECK (
        EXTRACT(DAY FROM ABERTURA) = 0
        AND EXTRACT(HOUR FROM ABERTURA) BETWEEN 0 AND 23
        AND EXTRACT(MINUTE FROM ABERTURA) BETWEEN 0 AND 59
        AND EXTRACT(SECOND FROM ABERTURA) = 0
    ),
    CONSTRAINT CK_LABORATORIO_FECHAMENTO_CHECK CHECK (
        EXTRACT(DAY FROM FECHAMENTO) = 0
        AND EXTRACT(HOUR FROM FECHAMENTO) BETWEEN 0 AND 23
        AND EXTRACT(MINUTE FROM FECHAMENTO) BETWEEN 0 AND 59
        AND EXTRACT(SECOND FROM FECHAMENTO) = 0
    ),
    
    CONSTRAINT CK_LABORATORIO_ESTADO CHECK (ESTADO IN (
        'AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA',
        'PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'
    )),
    
    CONSTRAINT CK_LABORATORIO_CIDADE_UPPER CHECK(UPPER(CIDADE) = CIDADE),
    CONSTRAINT CK_LABORATORIO_BAIRRO_UPPER CHECK(UPPER(BAIRRO) = BAIRRO),
    CONSTRAINT CK_LABORATORIO_RUA_UPPER CHECK(UPPER(RUA) = RUA),
    CONSTRAINT CK_LABORATORIO_NUMERO_POSITIVO CHECK(NUMERO > 0)
);

--Especialização Sala

CREATE TABLE SALA(
    HOSPITAL RAW(6) NOT NULL,
    --Deve ter o mesmo tamanho do número de salas máximo do hospital
    NUMERO NUMBER(4,0) NOT NULL,
    --DAY(0) e SECOND(0) impedem valores fracionários
    TEMPO_HIGIENIZACAO INTERVAL DAY(0) TO SECOND(0) NOT NULL,
    INICIO_ULTIMA_LIMPEZA DATE NOT NULL,
    TIPO CHAR(1) NOT NULL,
    
    CONSTRAINT PK_SALA PRIMARY KEY(HOSPITAL, NUMERO),
    CONSTRAINT FK_SALA_HOSPITAL FOREIGN KEY(HOSPITAL) REFERENCES HOSPITAL(ID),
    
    CONSTRAINT CK_SALA_TEMPO_HIGIENIZACAO_RAZOAVEL CHECK(TEMPO_HIGIENIZACAO < INTERVAL '1' DAY),
    --Não é possível avaliar se a última limpeza está no futuro, fica pra aplicação cuidar disso
    
    --C = CIRURGIA, I = INTERNAÇÃO
    CONSTRAINT CK_SALA_TIPO CHECK(TIPO IN ('C', 'I'))
);

CREATE TABLE SALA_INTERNACAO(
    HOSPITAL RAW(6) NOT NULL,
    NUMERO NUMBER(4,0) NOT NULL,
    NUMERO_LEITOS NUMBER(2,0) NOT NULL,
    
    CONSTRAINT PK_SALA_INTERNACAO PRIMARY KEY(HOSPITAL, NUMERO),
    CONSTRAINT FK_SALA_INTERNACAO_HOSPITAL_E_NUMERO FOREIGN KEY(HOSPITAL, NUMERO) REFERENCES SALA(HOSPITAL, NUMERO),
    
    CONSTRAINT CK_SALA_INTERNACAO_NUMERO_LEITOS_POSITIVO CHECK(NUMERO_LEITOS > 0)
);

CREATE TABLE SALA_CIRURGICA(
    HOSPITAL RAW(6) NOT NULL,
    NUMERO NUMBER(4,0) NOT NULL,
    
    CONSTRAINT PK_SALA_CIRURGICA PRIMARY KEY(HOSPITAL, NUMERO),
    CONSTRAINT FK_SALA_CIRURGICA_HOSPITAL_E_NUMERO FOREIGN KEY(HOSPITAL, NUMERO) REFERENCES SALA(HOSPITAL, NUMERO)
);

--Agregações

CREATE TABLE CIRURGIA(
    --https://www.gov.br/saude/pt-br/assuntos/noticias/2025/janeiro/ministerio-da-saude-registra-o-maior-numero-de-cirurgias-eletivas-da-historia-do-sus
    --13.663 milhões de operações em 2023
    --INT -> 4 bytes -> 2.147 bilhões de positivos, levaria 157 anos para preencher
    --Como a prioridade não é a confidenciabilidade, pode fazer por sequência e só com 4 bytes
    ID INT GENERATED ALWAYS AS IDENTITY,
    PACIENTE RAW(8) NOT NULL,
    HOSPITAL RAW(6) NOT NULL,
    NUMERO_SALA NUMBER(4,0) NOT NULL,
    DATA_HORARIO_INICIO DATE NOT NULL,
    DATA_HORARIO_TERMINO DATE NOT NULL,
    TIPO CHAR(1),
    
    CONSTRAINT PK_CIRURGIA PRIMARY KEY(ID),
    CONSTRAINT UNIQUE_CIRURGIA_INFO UNIQUE(PACIENTE, HOSPITAL, NUMERO_SALA, DATA_HORARIO_INICIO),
    
    CONSTRAINT FK_CIRURGIA_PACIENTE FOREIGN KEY(PACIENTE) REFERENCES PACIENTE(PESSOA),
    CONSTRAINT FK_CIRURGIA_HOSPITAL_E_NUMERO_SALA FOREIGN KEY(HOSPITAL, NUMERO_SALA) REFERENCES SALA_CIRURGICA(HOSPITAL, NUMERO),
    
    --C = COLETA, R = RECEPÇÃO
    CONSTRAINT CK_CIRURGIA_TIPO CHECK(TIPO IN ('C', 'R'))
);

CREATE TABLE CIRURGIA_COLETA(
    CIRURGIA INT NOT NULL,
    
    CONSTRAINT PK_CIRURGIA_COLETA PRIMARY KEY(CIRURGIA),
    CONSTRAINT FK_CIRURGIA_COLETA_CIRURGIA FOREIGN KEY(CIRURGIA) REFERENCES CIRURGIA(ID)
);

CREATE TABLE CIRURGIA_RECEPCAO(
    CIRURGIA INT NOT NULL,
    
    CONSTRAINT PK_CIRURGIA_RECEPCAO PRIMARY KEY(CIRURGIA),
    CONSTRAINT FK_CIRURGIA_RECEPCAO_CIRURGIA FOREIGN KEY(CIRURGIA) REFERENCES CIRURGIA(ID)
);

CREATE TABLE INTERNACAO(
    PACIENTE RAW(8) NOT NULL,
    HOSPITAL RAW(6) NOT NULL,
    NUMERO NUMBER(4,0) NOT NULL,
    DATA_HORARIO_ENTRADA DATE NOT NULL,
    DATA_HORARIO_ALTA DATE,
    
    CONSTRAINT PK_INTERNACAO PRIMARY KEY(PACIENTE, HOSPITAL, NUMERO, DATA_HORARIO_ENTRADA),
    CONSTRAINT FK_INTERNACAO_PACIENTE FOREIGN KEY(PACIENTE) REFERENCES PACIENTE(PESSOA),
    CONSTRAINT FK_INTERNACAO_HOSPITAL_E_NUMERO FOREIGN KEY(HOSPITAL, NUMERO) REFERENCES SALA_INTERNACAO(HOSPITAL, NUMERO)
);

CREATE TABLE EXAME(
    --https://saude.abril.com.br/medicina/mais-de-25-bilhoes-de-exames-foram-feitos-no-brasil-em-2024-podemos-comemorar/
    --1.34 bilhões de exames em 2024 só no SUS
    --NUMBER(13) -> até 9.999 trilhões, levaria 746 anos para preencher (considerando apenas o SUS)
    ID NUMBER(13) GENERATED ALWAYS AS IDENTITY,
    PACIENTE RAW(8) NOT NULL,
    LABORATORIO RAW(6) NOT NULL,
    DATA_HORARIO DATE NOT NULL,
    TIPO VARCHAR2(30) NOT NULL,
    MEDICO_SUPERVISOR RAW(8) NOT NULL,
    RESULTADO VARCHAR2(100),
    
    CONSTRAINT PK_EXAME PRIMARY KEY(ID),
    CONSTRAINT UNIQUE_EXAME_PACIENTE_LABORATORIO_DATA_HORARIO UNIQUE(PACIENTE, LABORATORIO, DATA_HORARIO),
    
    CONSTRAINT FK_EXAME_PACIENTE FOREIGN KEY(PACIENTE) REFERENCES PACIENTE(PESSOA),
    CONSTRAINT FK_EXAME_LABORATORIO FOREIGN KEY(LABORATORIO) REFERENCES LABORATORIO(ID),
    CONSTRAINT FK_EXAME_TIPO FOREIGN KEY(TIPO) REFERENCES TIPOS_EXAME(TIPO),
    CONSTRAINT FK_EXAME_MEDICO_SUPERVISOR FOREIGN KEY(MEDICO_SUPERVISOR) REFERENCES MEDICO(FUNCIONARIO),
    
    CONSTRAINT CK_EXAME_RESULTADO_UPPER CHECK(UPPER(RESULTADO) = RESULTADO)
);

CREATE TABLE ORGAO(
    TIPO VARCHAR2(20) NOT NULL,
    COLETA INT NOT NULL,
    LADO VARCHAR2(11) NOT NULL,
    RECEPCAO INT,
    TAMANHO FLOAT NOT NULL,
    PESO FLOAT NOT NULL,
    TIPO_SANGUINEO VARCHAR2(2) NOT NULL,
    RH CHAR(1) NOT NULL,
    HLA VARCHAR2(22) NOT NULL,
    
    CONSTRAINT PK_ORGAO PRIMARY KEY(TIPO, COLETA, LADO),
    CONSTRAINT FK_ORGAO_TIPO FOREIGN KEY(TIPO) REFERENCES TIPO_ORGAO(NOME),
    CONSTRAINT FK_ORGAO_COLETA FOREIGN KEY(COLETA) REFERENCES CIRURGIA_COLETA(CIRURGIA),
    CONSTRAINT FK_ORGAO_RECEPCAO FOREIGN KEY(RECEPCAO) REFERENCES CIRURGIA_RECEPCAO(CIRURGIA),
    
    CONSTRAINT CK_ORGAO_LADO CHECK(LADO IN ('ESQUERDO', 'DIREITO', 'INDIFERENTE')),
    
    CONSTRAINT CK_ORGAO_TAMANHO_POSITIVO CHECK(TAMANHO > 0),
    CONSTRAINT CK_ORGAO_PESO_POSITIVO CHECK(PESO > 0),
    
    CONSTRAINT CK_ORGAO_TIPO_SANGUINEO CHECK(TIPO_SANGUINEO IN ('A', 'B', 'O', 'AB')),
    CONSTRAINT CK_ORGAO_RH CHECK(RH IN ('+', '-')),
    --https://hla.alleles.org/pages/nomenclature/naming_alleles/
    --https://www.ebi.ac.uk/ipd/imgt/hla/about/statistics/
    CONSTRAINT CK_ORGAO_HLA CHECK(REGEXP_LIKE(HLA, '^HLA-(A|B|C|E|F|G|DPA1|DPB1|DQA1|DQB1|DRA|DRB1|DRB3|DRB4|DRB5|DMA|DMB|DOA|DOB)\*[0-9]{2,3}(:[0-9]{2}){0,3}(?:N|L|S|C|A|Q)?$'))
);

--Atributos multivalorados variáveis

CREATE TABLE HISTORICO_PACIENTE(
    PACIENTE RAW(8) NOT NULL,
    DATA_HORARIO DATE NOT NULL,
    CID CHAR(3) NOT NULL,
    DESCRICAO VARCHAR2(100),
    
    CONSTRAINT PK_HISTORICO_PACIENTE PRIMARY KEY(PACIENTE, DATA_HORARIO),
    CONSTRAINT FK_HISTORICO_PACIENTE_PACIENTE FOREIGN KEY(PACIENTE) REFERENCES PACIENTE(PESSOA),
    
    CONSTRAINT CK_HISTORICO_PACIENTE_CID CHECK(REGEXP_LIKE(CID, '[A-Z][0-9]{2}'))
);

-- Relacionamentos

CREATE TABLE RECEPTOR_ESPERA(
    RECEPTOR RAW(8) NOT NULL,
    TIPO_ORGAO VARCHAR2(20) NOT NULL,
    PRIORIDADE INT NOT NULL,
    
    CONSTRAINT PK_RECEPTOR_ESPERA PRIMARY KEY(RECEPTOR, TIPO_ORGAO),
    CONSTRAINT FK_RECEPTOR_ESPERA_RECEPTOR FOREIGN KEY(RECEPTOR) REFERENCES PACIENTE(PESSOA),
    CONSTRAINT FK_RECEPTOR_ESPERA_TIPO_ORGAO FOREIGN KEY(TIPO_ORGAO) REFERENCES TIPO_ORGAO(NOME),
    
    CONSTRAINT CK_RECEPTOR_ESPERA_PRIORIDADE_POSITIVO CHECK(PRIORIDADE > 0)
);

CREATE TABLE DOADOR_DOA(
    DOADOR RAW(8) NOT NULL,
    TIPO_ORGAO VARCHAR2(20) NOT NULL,
    
    CONSTRAINT PK_DOADOR_DOA PRIMARY KEY(DOADOR, TIPO_ORGAO),
    CONSTRAINT FK_DOADOR_DOA_DOADOR FOREIGN KEY(DOADOR) REFERENCES PACIENTE(PESSOA),
    CONSTRAINT FK_DOADOR_DOA_TIPO_ORGAO FOREIGN KEY(TIPO_ORGAO) REFERENCES TIPO_ORGAO(NOME)
);

CREATE TABLE TRABALHA(
    FUNCIONARIO RAW(8) NOT NULL,
    HOSPITAL RAW(6) NOT NULL,
    
    CONSTRAINT PK_TRABALHA PRIMARY KEY(FUNCIONARIO, HOSPITAL),
    CONSTRAINT FK_TRABALHA_FUNCIONARIO FOREIGN KEY(FUNCIONARIO) REFERENCES FUNCIONARIO(PESSOA),
    CONSTRAINT FK_TRABALHA_HOSPITAL FOREIGN KEY(HOSPITAL) REFERENCES HOSPITAL(ID)
);

CREATE TABLE OPERA(
    MEDICO RAW(8) NOT NULL,
    CIRURGIA INT NOT NULL,
    
    CONSTRAINT PK_OPERA PRIMARY KEY(MEDICO, CIRURGIA),
    CONSTRAINT FK_OPERA_MEDICO FOREIGN KEY(MEDICO) REFERENCES MEDICO(FUNCIONARIO),
    CONSTRAINT FK_OPERA_CIRURGIA FOREIGN KEY(CIRURGIA) REFERENCES CIRURGIA(ID)
);

CREATE TABLE AUXILIA(
    ENFERMEIRO RAW(8) NOT NULL,
    CIRURGIA INT NOT NULL,
    
    CONSTRAINT PK_AUXILIA PRIMARY KEY(ENFERMEIRO, CIRURGIA),
    CONSTRAINT FK_AUXILIA_ENFERMEIRO FOREIGN KEY(ENFERMEIRO) REFERENCES ENFERMEIRO(FUNCIONARIO),
    CONSTRAINT FK_AUXILIA_CIRURGIA FOREIGN KEY(CIRURGIA) REFERENCES CIRURGIA(ID)
);

CREATE TABLE EXAMES_DISPONIVEIS(
    LABORATORIO RAW(6) NOT NULL,
    TIPO VARCHAR2(30) NOT NULL,
    
    CONSTRAINT PK_EXAMES_DISPONIVEIS PRIMARY KEY(LABORATORIO, TIPO),
    CONSTRAINT FK_EXAMES_DISPONIVEIS_LABORATORIO FOREIGN KEY(LABORATORIO) REFERENCES LABORATORIO(ID),
    CONSTRAINT FK_EXAMES_DISPONIVEIS_TIPO FOREIGN KEY(TIPO) REFERENCES TIPOS_EXAME(TIPO)
);

CREATE TABLE AUTORIZACAO_HOSPITAL(
    HOSPITAL RAW(6) NOT NULL,
    AUTORIZACAO_SNT VARCHAR2(30) NOT NULL,
    VALIDADE_AUTORIZACAO DATE NOT NULL,
    
    CONSTRAINT PK_AUTORIZACAO_HOSPITAL PRIMARY KEY(HOSPITAL, AUTORIZACAO_SNT),
    CONSTRAINT FK_AUTORIZACAO_HOSPITAL_HOSPITAL FOREIGN KEY(HOSPITAL) REFERENCES HOSPITAL(ID),
    CONSTRAINT FK_AUTORIZACAO_HOSPITAL_AUTORIZACAO_SNT FOREIGN KEY(AUTORIZACAO_SNT) REFERENCES AUTORIZACOES_SNT(TIPO)
    
    --Não é possível avaliar se a validade se encontra no futuro, a aplicação vai precisar cuidar disso
);

CREATE TABLE EQUIPAMENTO_SALA_CIRURGICA(
    HOSPITAL RAW(6) NOT NULL,
    NUMERO NUMBER(4,0) NOT NULL,
    TIPO_EQUIPAMENTO VARCHAR2(50) NOT NULL,
    QUANTIDADE NUMBER(2,0) NOT NULL,
    
    CONSTRAINT PK_EQUIPAMENTO_SALA_CIRURGICA PRIMARY KEY(HOSPITAL, NUMERO, TIPO_EQUIPAMENTO),
    CONSTRAINT FK_EQUIPAMENTO_SALA_CIRURGICA_HOSPITAL_E_NUMERO FOREIGN KEY(HOSPITAL, NUMERO) REFERENCES SALA_CIRURGICA(HOSPITAL, NUMERO),
    CONSTRAINT FK_EQUIPAMENTO_SALA_CIRURGICA_TIPO_EQUIPAMENTO FOREIGN KEY(TIPO_EQUIPAMENTO) REFERENCES EQUIPAMENTO(TIPO),
    
    CONSTRAINT CK_EQUIPAMENTO_SALA_CIRURGICA_QUANTIDADE_POSITIVA CHECK(QUANTIDADE > 0)
);

--SELECT 'DROP TABLE '||TABLE_NAME||' CASCADE CONSTRAINTS;' FROM USER_TABLES;